[2023-06-13T17:15:05.891+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-13T17:07:11.104428+00:00 [queued]>
[2023-06-13T17:15:05.924+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-13T17:07:11.104428+00:00 [queued]>
[2023-06-13T17:15:05.925+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T17:15:05.933+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-06-13T17:15:05.934+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T17:15:05.974+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-13 17:07:11.104428+00:00
[2023-06-13T17:15:06.089+0000] {standard_task_runner.py:55} INFO - Started process 97 to run task
[2023-06-13T17:15:06.103+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-13T17:07:11.104428+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp6h3j2mos']
[2023-06-13T17:15:06.106+0000] {standard_task_runner.py:83} INFO - Job 34: Subtask download_dataset_task
[2023-06-13T17:15:06.266+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-13T17:07:11.104428+00:00 [running]> on host 2adc0c380f97
[2023-06-13T17:15:06.468+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-13T17:07:11.104428+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-13T17:07:11.104428+00:00
[2023-06-13T17:15:06.473+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-13T17:15:06.481+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'kaggle datasets download -d sherrytp/airline_delay_analysis > /opt/***/airline_delay_analysis.csv']
[2023-06-13T17:15:06.569+0000] {subprocess.py:86} INFO - Output:
[2023-06-13T17:15:08.097+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-13T17:15:08.125+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-13T17:15:08.148+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230613T170711, start_date=20230613T171505, end_date=20230613T171508
[2023-06-13T17:15:08.216+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 34 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 97)
[2023-06-13T17:15:08.238+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-13T17:15:08.342+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
