[2023-06-13T18:37:59.301+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-06-13T17:44:58.036409+00:00 [queued]>
[2023-06-13T18:37:59.315+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-06-13T17:44:58.036409+00:00 [queued]>
[2023-06-13T18:37:59.317+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T18:37:59.318+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-06-13T18:37:59.319+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T18:37:59.339+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-06-13 17:44:58.036409+00:00
[2023-06-13T18:37:59.360+0000] {standard_task_runner.py:55} INFO - Started process 3379 to run task
[2023-06-13T18:37:59.363+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'manual__2023-06-13T17:44:58.036409+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp4d20e7ik']
[2023-06-13T18:37:59.365+0000] {standard_task_runner.py:83} INFO - Job 47: Subtask local_to_gcs_task
[2023-06-13T18:37:59.443+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-06-13T17:44:58.036409+00:00 [running]> on host 2adc0c380f97
[2023-06-13T18:37:59.547+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-13T17:44:58.036409+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-13T17:44:58.036409+00:00
[2023-06-13T18:37:59.676+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 63, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2681, in upload_from_filename
    with open(filename, "rb") as file_obj:
IsADirectoryError: [Errno 21] Is a directory: '/opt/airflow/airline-delay-analysis'
[2023-06-13T18:37:59.709+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20230613T174458, start_date=20230613T183759, end_date=20230613T183759
[2023-06-13T18:37:59.855+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 47 for task local_to_gcs_task ([Errno 21] Is a directory: '/opt/airflow/airline-delay-analysis'; 3379)
[2023-06-13T18:37:59.899+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-13T18:37:59.932+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
