[2023-06-15T06:24:25.188+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T06:19:02.642551+00:00 [queued]>
[2023-06-15T06:24:25.205+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T06:19:02.642551+00:00 [queued]>
[2023-06-15T06:24:25.205+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T06:24:25.207+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-06-15T06:24:25.209+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T06:24:25.239+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 06:19:02.642551+00:00
[2023-06-15T06:24:25.280+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T06:19:02.642551+00:00', '--job-id', '315', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_kaggle.py', '--cfg-path', '/tmp/tmpvqjutwtu']
[2023-06-15T06:24:25.278+0000] {standard_task_runner.py:55} INFO - Started process 2622 to run task
[2023-06-15T06:24:25.284+0000] {standard_task_runner.py:83} INFO - Job 315: Subtask download_dataset_task
[2023-06-15T06:24:25.567+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T06:19:02.642551+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T06:24:25.826+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T06:19:02.642551+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T06:19:02.642551+00:00
[2023-06-15T06:24:25.833+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T06:24:25.852+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'kaggle datasets download -d sherrytp/airline-delay-analysis > /opt/***/']
[2023-06-15T06:24:25.889+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T06:24:25.913+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /opt/***/: Is a directory
[2023-06-15T06:24:25.916+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-15T06:24:25.944+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-15T06:24:25.962+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T061902, start_date=20230615T062425, end_date=20230615T062425
[2023-06-15T06:24:26.014+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 315 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 2622)
[2023-06-15T06:24:26.066+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T06:24:26.117+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
