[2023-06-13T18:51:14.846+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-06-13T18:50:55.688322+00:00 [queued]>
[2023-06-13T18:51:14.858+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-06-13T18:50:55.688322+00:00 [queued]>
[2023-06-13T18:51:14.860+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T18:51:14.861+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-13T18:51:14.862+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T18:51:14.881+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-06-13 18:50:55.688322+00:00
[2023-06-13T18:51:14.889+0000] {standard_task_runner.py:55} INFO - Started process 4170 to run task
[2023-06-13T18:51:14.892+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'manual__2023-06-13T18:50:55.688322+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpfg9ldevn']
[2023-06-13T18:51:14.894+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask local_to_gcs_task
[2023-06-13T18:51:14.964+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-06-13T18:50:55.688322+00:00 [running]> on host 2adc0c380f97
[2023-06-13T18:51:15.051+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-13T18:50:55.688322+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-13T18:50:55.688322+00:00
[2023-06-13T18:51:15.053+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: upload_directory_to_gcs() missing 1 required positional argument: 'bucket_name'
[2023-06-13T18:51:15.067+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20230613T185055, start_date=20230613T185114, end_date=20230613T185115
[2023-06-13T18:51:15.088+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 54 for task local_to_gcs_task (upload_directory_to_gcs() missing 1 required positional argument: 'bucket_name'; 4170)
[2023-06-13T18:51:15.108+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-13T18:51:15.136+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
