[2023-06-15T07:58:27.655+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2023-06-15T07:52:55.466683+00:00 [queued]>
[2023-06-15T07:58:27.680+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2023-06-15T07:52:55.466683+00:00 [queued]>
[2023-06-15T07:58:27.681+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T07:58:27.682+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-06-15T07:58:27.683+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T07:58:27.720+0000] {taskinstance.py:1303} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2023-06-15 07:52:55.466683+00:00
[2023-06-15T07:58:27.744+0000] {standard_task_runner.py:55} INFO - Started process 7769 to run task
[2023-06-15T07:58:27.748+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'manual__2023-06-15T07:52:55.466683+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmph8ucn41q']
[2023-06-15T07:58:27.750+0000] {standard_task_runner.py:83} INFO - Job 342: Subtask bigquery_external_table_task
[2023-06-15T07:58:27.849+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2023-06-15T07:52:55.466683+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T07:58:28.022+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T07:52:55.466683+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T07:52:55.466683+00:00
[2023-06-15T07:58:28.026+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-06-15T07:58:28.027+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-06-15T07:58:29.325+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1629, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 407, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/prime-byway-387902/datasets/project1_data/tables?prettyPrint=false: Error while reading table: external_table, error message: Input file is not in Parquet format. File: gs://myproject1-delay-airline/raw/data-science-salaries-2023
[2023-06-15T07:58:29.439+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20230615T075255, start_date=20230615T075827, end_date=20230615T075829
[2023-06-15T07:58:29.494+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 342 for task bigquery_external_table_task (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/prime-byway-387902/datasets/project1_data/tables?prettyPrint=false: Error while reading table: external_table, error message: Input file is not in Parquet format. File: gs://myproject1-delay-airline/raw/data-science-salaries-2023; 7769)
[2023-06-15T07:58:29.593+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T07:58:29.742+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
