[2023-06-15T13:04:47.838+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-06-15T13:04:16.689854+00:00 [queued]>
[2023-06-15T13:04:47.856+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-06-15T13:04:16.689854+00:00 [queued]>
[2023-06-15T13:04:47.859+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T13:04:47.860+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T13:04:47.862+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T13:04:47.902+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-06-15 13:04:16.689854+00:00
[2023-06-15T13:04:47.913+0000] {standard_task_runner.py:55} INFO - Started process 21019 to run task
[2023-06-15T13:04:47.917+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'manual__2023-06-15T13:04:16.689854+00:00', '--job-id', '421', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp34o6vne5']
[2023-06-15T13:04:47.923+0000] {standard_task_runner.py:83} INFO - Job 421: Subtask local_to_gcs_task
[2023-06-15T13:04:48.037+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-06-15T13:04:16.689854+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T13:04:48.160+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T13:04:16.689854+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T13:04:16.689854+00:00
[2023-06-15T13:04:48.365+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 52, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2681, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data-science-salaries-2023.csv'
[2023-06-15T13:04:48.399+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20230615T130416, start_date=20230615T130447, end_date=20230615T130448
[2023-06-15T13:04:48.422+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 421 for task local_to_gcs_task ([Errno 2] No such file or directory: '/opt/airflow/data-science-salaries-2023.csv'; 21019)
[2023-06-15T13:04:48.453+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T13:04:48.528+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
