[2023-06-16T00:34:20.181+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-16T00:34:08.930345+00:00 [queued]>
[2023-06-16T00:34:20.199+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-16T00:34:08.930345+00:00 [queued]>
[2023-06-16T00:34:20.200+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-16T00:34:20.203+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-16T00:34:20.203+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-16T00:34:20.235+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-16 00:34:08.930345+00:00
[2023-06-16T00:34:20.252+0000] {standard_task_runner.py:55} INFO - Started process 182 to run task
[2023-06-16T00:34:20.256+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-16T00:34:08.930345+00:00', '--job-id', '498', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpih4sqxvy']
[2023-06-16T00:34:20.259+0000] {standard_task_runner.py:83} INFO - Job 498: Subtask download_dataset_task
[2023-06-16T00:34:20.388+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-16T00:34:08.930345+00:00 [running]> on host 2a315e4d94ac
[2023-06-16T00:34:20.499+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-16T00:34:08.930345+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-16T00:34:08.930345+00:00
[2023-06-16T00:34:20.503+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-16T00:34:20.505+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        cd /opt/*** &&\n        if [ ! -d direct-messaging ]; then\n            mkdir direct-messaging &&\n            cd direct-messaging &&\n            wget kaggle datasets download -d mkechinov/direct-messaging -O direct-messaging.zip --quiet &&\n            unzip direct-messaging.zip && \n            rm direct-messaging.zip\n        elif [ -d direct-messaging ]; then\n            cd direct-messaging &&\n            ls\n        fi\n        ']
[2023-06-16T00:34:20.526+0000] {subprocess.py:86} INFO - Output:
[2023-06-16T00:34:20.582+0000] {subprocess.py:93} INFO - /bin/bash: line 6: wget: command not found
[2023-06-16T00:34:20.583+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-16T00:34:20.597+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-16T00:34:20.603+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230616T003408, start_date=20230616T003420, end_date=20230616T003420
[2023-06-16T00:34:20.632+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 498 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 127.; 182)
[2023-06-16T00:34:20.670+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-16T00:34:20.700+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
