[2023-06-13T16:01:10.306+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-06-13T16:01:10.324+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-06-13T16:01:10.325+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T16:01:10.327+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-13T16:01:10.328+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T16:01:10.355+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-12 00:00:00+00:00
[2023-06-13T16:01:10.409+0000] {standard_task_runner.py:55} INFO - Started process 340 to run task
[2023-06-13T16:01:10.417+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2023-06-12T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp2x64kfhs']
[2023-06-13T16:01:10.422+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask download_dataset_task
[2023-06-13T16:01:10.641+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2023-06-12T00:00:00+00:00 [running]> on host e2cbf344ce7f
[2023-06-13T16:01:10.850+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-12T00:00:00+00:00
[2023-06-13T16:01:10.858+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-13T16:01:10.864+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'kaggle datasets download -d sherrytp/airline_delay_analysis.csv > /opt/***/airline_delay_analysis.csv']
[2023-06-13T16:01:11.148+0000] {subprocess.py:86} INFO - Output:
[2023-06-13T16:01:11.329+0000] {subprocess.py:93} INFO - /bin/bash: line 1: kaggle: command not found
[2023-06-13T16:01:11.342+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-13T16:01:11.394+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-13T16:01:11.403+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230612T000000, start_date=20230613T160110, end_date=20230613T160111
[2023-06-13T16:01:11.481+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 127.; 340)
[2023-06-13T16:01:11.524+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-13T16:01:11.583+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
