[2023-06-15T12:13:07.016+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T12:12:51.873032+00:00 [queued]>
[2023-06-15T12:13:07.037+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T12:12:51.873032+00:00 [queued]>
[2023-06-15T12:13:07.038+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T12:13:07.039+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T12:13:07.040+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T12:13:07.075+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 12:12:51.873032+00:00
[2023-06-15T12:13:07.099+0000] {standard_task_runner.py:55} INFO - Started process 18045 to run task
[2023-06-15T12:13:07.108+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T12:12:51.873032+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpinkwl61h']
[2023-06-15T12:13:07.110+0000] {standard_task_runner.py:83} INFO - Job 409: Subtask download_dataset_task
[2023-06-15T12:13:07.229+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T12:12:51.873032+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T12:13:07.400+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T12:12:51.873032+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T12:12:51.873032+00:00
[2023-06-15T12:13:07.405+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T12:13:07.422+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            mkdir -p /opt/***/data-science-salaries-2023 &&\n            cd /opt/*** && kaggle datasets download -d arnabchaki/data-science-salaries-2023 && unzip data-science-salaries-2023.zip && rm data-science-salaries-2023.zip']
[2023-06-15T12:13:07.474+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T12:13:07.561+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/***/data-science-salaries-2023’: File exists
[2023-06-15T12:13:07.564+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-15T12:13:07.587+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-15T12:13:07.593+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T121251, start_date=20230615T121307, end_date=20230615T121307
[2023-06-15T12:13:07.631+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 409 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 18045)
[2023-06-15T12:13:07.681+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T12:13:07.740+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
