[2023-06-15T01:23:16.345+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2023-06-15T01:22:54.571162+00:00 [queued]>
[2023-06-15T01:23:16.359+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2023-06-15T01:22:54.571162+00:00 [queued]>
[2023-06-15T01:23:16.359+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T01:23:16.360+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T01:23:16.361+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T01:23:16.388+0000] {taskinstance.py:1303} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2023-06-15 01:22:54.571162+00:00
[2023-06-15T01:23:16.409+0000] {standard_task_runner.py:55} INFO - Started process 8197 to run task
[2023-06-15T01:23:16.414+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'manual__2023-06-15T01:22:54.571162+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpxe9y7hx8']
[2023-06-15T01:23:16.418+0000] {standard_task_runner.py:83} INFO - Job 218: Subtask bigquery_external_table_task
[2023-06-15T01:23:16.526+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2023-06-15T01:22:54.571162+00:00 [running]> on host 570ce802d94a
[2023-06-15T01:23:16.641+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T01:22:54.571162+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T01:22:54.571162+00:00
[2023-06-15T01:23:16.645+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-06-15T01:23:16.646+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-06-15T01:23:17.663+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1629, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 407, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/prime-byway-387902/datasets/project1_data/tables?prettyPrint=false: Error while reading table: external_table, error message: Failed to expand table external_table with file pattern gs://myproject1-delay-airline/raw/*.parquet: matched no files. File: gs://myproject1-delay-airline/raw/*.parquet
[2023-06-15T01:23:17.685+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20230615T012254, start_date=20230615T012316, end_date=20230615T012317
[2023-06-15T01:23:17.710+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 218 for task bigquery_external_table_task (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/prime-byway-387902/datasets/project1_data/tables?prettyPrint=false: Error while reading table: external_table, error message: Failed to expand table external_table with file pattern gs://myproject1-delay-airline/raw/*.parquet: matched no files. File: gs://myproject1-delay-airline/raw/*.parquet; 8197)
[2023-06-15T01:23:17.727+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T01:23:17.747+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
