[2023-06-15T17:12:53.452+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T17:12:48.792823+00:00 [queued]>
[2023-06-15T17:12:53.466+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T17:12:48.792823+00:00 [queued]>
[2023-06-15T17:12:53.467+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T17:12:53.468+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T17:12:53.469+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T17:12:53.491+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 17:12:48.792823+00:00
[2023-06-15T17:12:53.503+0000] {standard_task_runner.py:55} INFO - Started process 32344 to run task
[2023-06-15T17:12:53.507+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T17:12:48.792823+00:00', '--job-id', '452', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpyous_fgq']
[2023-06-15T17:12:53.511+0000] {standard_task_runner.py:83} INFO - Job 452: Subtask download_dataset_task
[2023-06-15T17:12:53.710+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T17:12:48.792823+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T17:12:53.862+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T17:12:48.792823+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T17:12:48.792823+00:00
[2023-06-15T17:12:53.869+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T17:12:53.878+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/*** &&\n            rm -f direct-messaging &&\n            mkdir direct-messaging &&\n            cd direct-messaging &&\n            kaggle datasets download -d mkechinov/direct-messaging --force && \n            unzip direct-messaging.zip && \n            rm direct-messaging.zip\n            ']
[2023-06-15T17:12:53.934+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T17:12:53.936+0000] {subprocess.py:93} INFO - rm: cannot remove 'direct-messaging': Is a directory
[2023-06-15T17:12:53.937+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-15T17:12:53.961+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-15T17:12:53.969+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T171248, start_date=20230615T171253, end_date=20230615T171253
[2023-06-15T17:12:54.012+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 452 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 32344)
[2023-06-15T17:12:54.043+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T17:12:54.089+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
