[2023-06-15T11:41:03.826+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T11:40:57.112357+00:00 [queued]>
[2023-06-15T11:41:03.848+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T11:40:57.112357+00:00 [queued]>
[2023-06-15T11:41:03.849+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T11:41:03.851+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T11:41:03.852+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T11:41:03.881+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 11:40:57.112357+00:00
[2023-06-15T11:41:03.898+0000] {standard_task_runner.py:55} INFO - Started process 16397 to run task
[2023-06-15T11:41:03.906+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T11:40:57.112357+00:00', '--job-id', '398', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpfsus5ld6']
[2023-06-15T11:41:03.910+0000] {standard_task_runner.py:83} INFO - Job 398: Subtask download_dataset_task
[2023-06-15T11:41:04.214+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T11:40:57.112357+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T11:41:04.525+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T11:40:57.112357+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T11:40:57.112357+00:00
[2023-06-15T11:41:04.528+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T11:41:04.544+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'kaggle datasets download -d arnabchaki/data-science-salaries-2023 -p /opt/***/data-science-salaries-2023.zip']
[2023-06-15T11:41:04.614+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T11:41:07.589+0000] {subprocess.py:93} INFO - Downloading data-science-salaries-2023.zip to /opt/***/data-science-salaries-2023.zip
[2023-06-15T11:41:07.591+0000] {subprocess.py:93} INFO -   0%|          | 0.00/25.4k [00:00<?, ?B/s]  0%|          | 0.00/25.4k [00:00<?, ?B/s]
[2023-06-15T11:41:07.600+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-06-15T11:41:07.602+0000] {subprocess.py:93} INFO -   File "/home/***/.local/bin/kaggle", line 8, in <module>
[2023-06-15T11:41:07.603+0000] {subprocess.py:93} INFO -     sys.exit(main())
[2023-06-15T11:41:07.604+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kaggle/cli.py", line 67, in main
[2023-06-15T11:41:07.605+0000] {subprocess.py:93} INFO -     out = args.func(**command_args)
[2023-06-15T11:41:07.606+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 1287, in dataset_download_cli
[2023-06-15T11:41:07.607+0000] {subprocess.py:93} INFO -     quiet=quiet)
[2023-06-15T11:41:07.608+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 1236, in dataset_download_files
[2023-06-15T11:41:07.608+0000] {subprocess.py:93} INFO -     self.download_file(response, outfile, quiet)
[2023-06-15T11:41:07.609+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 1594, in download_file
[2023-06-15T11:41:07.610+0000] {subprocess.py:93} INFO -     with open(outfile, 'wb') as out:
[2023-06-15T11:41:07.611+0000] {subprocess.py:93} INFO - NotADirectoryError: [Errno 20] Not a directory: '/opt/***/data-science-salaries-2023.zip/data-science-salaries-2023.zip'
[2023-06-15T11:41:07.683+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-15T11:41:07.720+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-15T11:41:07.743+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T114057, start_date=20230615T114103, end_date=20230615T114107
[2023-06-15T11:41:07.779+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 398 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 16397)
[2023-06-15T11:41:07.809+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T11:41:07.856+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
