[2023-06-14T11:09:18.778+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2023-06-14T10:56:08.405936+00:00 [queued]>
[2023-06-14T11:09:18.801+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2023-06-14T10:56:08.405936+00:00 [queued]>
[2023-06-14T11:09:18.803+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T11:09:18.804+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-06-14T11:09:18.805+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T11:09:18.841+0000] {taskinstance.py:1303} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2023-06-14 10:56:08.405936+00:00
[2023-06-14T11:09:18.859+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'manual__2023-06-14T10:56:08.405936+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpfg6_gr1f']
[2023-06-14T11:09:18.855+0000] {standard_task_runner.py:55} INFO - Started process 10401 to run task
[2023-06-14T11:09:18.862+0000] {standard_task_runner.py:83} INFO - Job 145: Subtask bigquery_external_table_task
[2023-06-14T11:09:19.008+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2023-06-14T10:56:08.405936+00:00 [running]> on host 2adc0c380f97
[2023-06-14T11:09:19.366+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-14T10:56:08.405936+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-14T10:56:08.405936+00:00
[2023-06-14T11:09:19.370+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-06-14T11:09:19.372+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-06-14T11:09:20.212+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1629, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 407, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/prime-byway-387902/datasets/project1_data/tables?prettyPrint=false: Invalid source URI: ['gs://myproject1-delay-airline/raw/airline-delay-analysis.zip']
[2023-06-14T11:09:20.349+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20230614T105608, start_date=20230614T110918, end_date=20230614T110920
[2023-06-14T11:09:20.412+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 145 for task bigquery_external_table_task (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/prime-byway-387902/datasets/project1_data/tables?prettyPrint=false: Invalid source URI: ['gs://myproject1-delay-airline/raw/airline-delay-analysis.zip']; 10401)
[2023-06-14T11:09:20.435+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-14T11:09:20.477+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
