[2023-06-13T17:15:51.342+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-13T17:15:46.466761+00:00 [queued]>
[2023-06-13T17:15:51.354+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-13T17:15:46.466761+00:00 [queued]>
[2023-06-13T17:15:51.356+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T17:15:51.357+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-13T17:15:51.358+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T17:15:51.381+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-13 17:15:46.466761+00:00
[2023-06-13T17:15:51.422+0000] {standard_task_runner.py:55} INFO - Started process 156 to run task
[2023-06-13T17:15:51.426+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-13T17:15:46.466761+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpgey37uvo']
[2023-06-13T17:15:51.430+0000] {standard_task_runner.py:83} INFO - Job 35: Subtask download_dataset_task
[2023-06-13T17:15:51.559+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-13T17:15:46.466761+00:00 [running]> on host 2adc0c380f97
[2023-06-13T17:15:51.649+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-13T17:15:46.466761+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-13T17:15:46.466761+00:00
[2023-06-13T17:15:51.651+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-13T17:15:51.655+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'kaggle datasets download -d sherrytp/airline_delay_analysis > /opt/***/airline_delay_analysis.csv']
[2023-06-13T17:15:51.685+0000] {subprocess.py:86} INFO - Output:
[2023-06-13T17:15:52.665+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-13T17:15:52.678+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-13T17:15:52.684+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230613T171546, start_date=20230613T171551, end_date=20230613T171552
[2023-06-13T17:15:52.706+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 35 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 156)
[2023-06-13T17:15:52.724+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-13T17:15:52.755+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
