[2023-06-13T17:04:09.835+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-13T17:03:32.462731+00:00 [queued]>
[2023-06-13T17:04:09.855+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-13T17:03:32.462731+00:00 [queued]>
[2023-06-13T17:04:09.856+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T17:04:09.858+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-13T17:04:09.859+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T17:04:09.887+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-13 17:03:32.462731+00:00
[2023-06-13T17:04:09.904+0000] {standard_task_runner.py:55} INFO - Started process 321 to run task
[2023-06-13T17:04:09.908+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-13T17:03:32.462731+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpvnhzeiau']
[2023-06-13T17:04:09.911+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask download_dataset_task
[2023-06-13T17:04:10.051+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-13T17:03:32.462731+00:00 [running]> on host 2adc0c380f97
[2023-06-13T17:04:10.160+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-13T17:03:32.462731+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-13T17:03:32.462731+00:00
[2023-06-13T17:04:10.163+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-13T17:04:10.165+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'kaggle datasets download -d sherrytp/airline_delay_analysis > /opt/***/airline_delay_analysis']
[2023-06-13T17:04:10.188+0000] {subprocess.py:86} INFO - Output:
[2023-06-13T17:04:11.819+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-13T17:04:11.835+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-13T17:04:11.844+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230613T170332, start_date=20230613T170409, end_date=20230613T170411
[2023-06-13T17:04:11.877+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 30 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 321)
[2023-06-13T17:04:11.929+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-13T17:04:12.051+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
