[2023-06-15T13:12:18.999+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T13:12:05.697206+00:00 [queued]>
[2023-06-15T13:12:19.013+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T13:12:05.697206+00:00 [queued]>
[2023-06-15T13:12:19.015+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T13:12:19.016+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T13:12:19.016+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T13:12:19.044+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 13:12:05.697206+00:00
[2023-06-15T13:12:19.055+0000] {standard_task_runner.py:55} INFO - Started process 21453 to run task
[2023-06-15T13:12:19.058+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T13:12:05.697206+00:00', '--job-id', '429', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpg0sjp2n0']
[2023-06-15T13:12:19.061+0000] {standard_task_runner.py:83} INFO - Job 429: Subtask download_dataset_task
[2023-06-15T13:12:19.173+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T13:12:05.697206+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T13:12:19.285+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T13:12:05.697206+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T13:12:05.697206+00:00
[2023-06-15T13:12:19.287+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T13:12:19.293+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/*** &&\n            cd data-science-salaries-2023 &&\n            kaggle datasets download -d arnabchaki/data-science-salaries-2023 --force && \n            unzip data-science-salaries-2023.zip && \n            rm data-science-salaries-2023.zip\n            ']
[2023-06-15T13:12:19.320+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T13:12:21.081+0000] {subprocess.py:93} INFO - Downloading data-science-salaries-2023.zip to /opt/***/data-science-salaries-2023
[2023-06-15T13:12:21.101+0000] {subprocess.py:93} INFO -   0%|          | 0.00/25.4k [00:00<?, ?B/s]100%|██████████| 25.4k/25.4k [00:00<00:00, 1.41MB/s]
[2023-06-15T13:12:21.102+0000] {subprocess.py:93} INFO - 
[2023-06-15T13:12:21.245+0000] {subprocess.py:93} INFO - Archive:  data-science-salaries-2023.zip
[2023-06-15T13:12:21.247+0000] {subprocess.py:93} INFO - replace ds_salaries.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
[2023-06-15T13:12:21.249+0000] {subprocess.py:93} INFO - (EOF or read error, treating as "[N]one" ...)
[2023-06-15T13:12:21.250+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-15T13:12:21.267+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-15T13:12:21.274+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T131205, start_date=20230615T131219, end_date=20230615T131221
[2023-06-15T13:12:21.296+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 429 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 21453)
[2023-06-15T13:12:21.323+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T13:12:21.361+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
