[2023-06-15T18:09:01.652+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T18:03:42.154983+00:00 [queued]>
[2023-06-15T18:09:01.786+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T18:03:42.154983+00:00 [queued]>
[2023-06-15T18:09:01.798+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T18:09:01.818+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-06-15T18:09:01.842+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T18:09:01.881+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 18:03:42.154983+00:00
[2023-06-15T18:09:01.907+0000] {standard_task_runner.py:55} INFO - Started process 2731 to run task
[2023-06-15T18:09:01.911+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T18:03:42.154983+00:00', '--job-id', '475', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpddk6anbi']
[2023-06-15T18:09:01.915+0000] {standard_task_runner.py:83} INFO - Job 475: Subtask download_dataset_task
[2023-06-15T18:09:02.071+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T18:03:42.154983+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T18:09:02.356+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T18:03:42.154983+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T18:03:42.154983+00:00
[2023-06-15T18:09:02.363+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T18:09:02.388+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        cd /opt/*** &&\n        if [ ! -d direct-messaging ]; then\n            mkdir direct-messaging &&\n            cd direct-messaging &&\n            kaggle datasets download -d mkechinov/direct-messaging --force &&\n            unzip direct-messaging.zip && \n            rm direct-messaging.zip &&\n        fi &&\n        cd direct-messaging &&\n        ls &&\n        ']
[2023-06-15T18:09:02.450+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T18:09:02.582+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 9: syntax error near unexpected token `fi'
[2023-06-15T18:09:02.584+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 9: `        fi &&'
[2023-06-15T18:09:02.587+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-06-15T18:09:02.623+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-15T18:09:02.640+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T180342, start_date=20230615T180901, end_date=20230615T180902
[2023-06-15T18:09:02.762+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 475 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 2.; 2731)
[2023-06-15T18:09:02.826+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T18:09:02.923+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
